## This is just a practice notebook where I manipulate tensors and experiment with different data types. Basically i'm fiddling around in the data pre-processing stage.


# Working with Images

An image is represented as a collection of scalars arranged in a regular grid with a
height and a width (in pixels). We might have a single scalar per grid point (the
pixel), which would be represented as a grayscale image; or multiple scalars per grid
point, which would typically represent different colors

In [3]:
import imageio as im

img_arr = im.imread('oppie.jpeg')

<ipython-input-3-b6da11ef2a94>:3: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = im.imread('oppie.jpeg')


In [6]:
img_arr.shape # the output is in the form of H x W x C

(2910, 5174, 3)

In [5]:
# note that the proper layout for image arrays is C x H x W for PyTorch. We need to convert the images into that if required.

In [7]:
import torch

img = torch.from_numpy(img_arr)
out = img.permute(2,0,1) #inplace operation
out.shape

torch.Size([3, 2910, 5174])

In [14]:
batch_size = 3
batch = torch.zeros(batch_size,6)

In [15]:
import os

data_dir = 'oppie_img_data/'
filenames = [name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == '.png']

for i, filename in enumerate(filenames):
  img_arr = im.imread(os.path.join(data_dir,filename))
  img_t = torch.from_numpy(img_arr)
  img_t = img_t.permute(2,0,1)
  img_t = img_t[:3]
  batch[i] = img_t

# Working with Tabular Data

 PyTorch tensors, on the other hand, are homogeneous. Information in PyTorch is
typically encoded as a number, typically floating-point (though integer types and
Boolean are supported as well). This numeric encoding is deliberate, since neural
networks are mathematical entities that take real numbers as inputs and produce real
numbers as output through successive application of matrix multiplications and
nonlinear functions.

In [17]:
import csv
wine_path = 'winequality-white.csv'

In [18]:
# Instead of pandas, let's import this using numpy

In [23]:
import numpy as np
wine_num =  np.loadtxt(wine_path,dtype = np.float32, delimiter = ';',skiprows = 1)

In [24]:
wine_num

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [25]:
wineq = torch.from_numpy(wine_num)

In [26]:
wineq.type, wineq.shape

(<function Tensor.type>, torch.Size([4898, 12]))

In [27]:
data = wineq[:,:-1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [29]:
target = wineq[:,-1]
target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))